name: Changesets - Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: changesets-release
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - name: Version / Publish with Changesets
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: pnpm run changeset:version
          publish: pnpm run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
